__Numpy Arrays__

In [1]:
import numpy as np

__1D Numpy Arrays__

In [2]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
print(list)

arr = np.array(list)
print(arr)

[20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
[20 27  9 12 31 17  4 50 39 35]


In [3]:
print(arr * 4)

[ 80 108  36  48 124  68  16 200 156 140]


In [4]:
print(np.mean(arr))

24.4


In [5]:
print(np.median(arr))

23.5


In [6]:
print(np.std(arr))

13.828955130450023


In [7]:
print(f"The index of the smallest number is {np.argmin(arr)}")
print(f"The index of the largest number is {np.argmax(arr)}")

The index of the smallest number is 6
The index of the largest number is 7


In [8]:
print(arr[6])
print(arr[7])

4
50


In [9]:
print(f"The smallest number is {np.min(arr)}")
print(f"The largest number is {np.max(arr)}")

print("\nThey match the numbers from the previous step")

The smallest number is 4
The largest number is 50

They match the numbers from the previous step


In [10]:
new_arr = arr[arr > 20]
print(new_arr)

[27 31 50 39 35]


__2D Numpy Arrays__

In [11]:
matrix = np.array([
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
])
print(np.shape(matrix))

(3, 4)


In [12]:
print("Third column:\n", matrix[:, 2])

Third column:
 [17 14 19]


In [13]:
print("Second row:\n", matrix[1, :])

Second row:
 [ 8 21 14  3]


In [14]:
print(matrix * 2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [15]:
print("Mean of each column:\n", np.mean(matrix, axis=0))

Mean of each column:
 [ 6.33333333 15.33333333 16.66666667  7.66666667]


In [16]:
print(np.mean(matrix))

11.5


In [17]:
print(
    f"The max value in each row:\n{np.max(matrix, axis=1)}\n"
    f"The minimum value in each column:\n{np.min(matrix, axis=0)}"
)     

The max value in each row:
[17 21 19]
The minimum value in each column:
[ 5 12 14  3]


In [18]:
flattened = matrix.flatten()
print(
    f"{flattened}\nThe new shape is {np.shape(flattened)}\nWhat happened is that .flatten() "
    "turned our 2D array into a 1D array."
)

[ 5 12 17  9  8 21 14  3  6 13 19 11]
The new shape is (12,)
What happened is that .flatten() turned our 2D array into a 1D array.


In [19]:
flat_min_index = np.argmin(flattened)
flat_max_index = np.argmax(flattened)
print(f"The index of the smallest number is {flat_min_index}")
print(f"The index of the largest number is {flat_max_index}")

The index of the smallest number is 7
The index of the largest number is 5


In [20]:
min_coords = np.unravel_index(flat_min_index, matrix.shape)
max_coords = np.unravel_index(flat_max_index, matrix.shape)

# Convert to regular int
min_coords = tuple(int(x) for x in min_coords)
max_coords = tuple(int(x) for x in max_coords)

print("Row-column of smallest value:", min_coords)
print("Row-column of largest value:", max_coords)

Row-column of smallest value: (1, 3)
Row-column of largest value: (1, 1)


In [21]:
greater_15 = matrix[matrix >15]
print(f"New array with values greater than 15: {greater_15}")

New array with values greater than 15: [17 21 19]


In [22]:
print(f"Row-sorted array:\n {np.sort(matrix)}")

Row-sorted array:
 [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


__Prime Star Systems__

In [23]:
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def is_prime(n):
    """Return True if n is a prime number."""
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

def rows_with_prime(arr):
    """Return only the rows from array where at least one element is prime."""
    mask = [any(is_prime(x) for x in row) for row in arr]
    return arr[mask]

result = rows_with_prime(arr)
print("Rows with at least one prime number:\n", result)

Rows with at least one prime number:
 [[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


__Let's Play Checkers__

In [24]:
def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, ::2] = 1   # even rows, even columns
    board[1::2, 1::2] = 1 # odd rows, odd columns
    return board

print("Checkerboard:\n", checkerboard())

Checkerboard:
 [[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [25]:
def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2, 1::2] = 1  # even rows, odd columns
    board[1::2, ::2] = 1  # odd rows, even columns
    return board

print("Reverse checkerboard:\n", reverse_checkerboard())

Reverse checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


__The Expanding Universe__

In [26]:
def expansion(strings, n):
    """Return each string with n spaces between letters."""
    spaces = ' ' * n  # create the spacing
    expanded = [spaces.join(ch) for ch in strings]
    return expanded
    
universe = np.array(['galaxy', 'clusters'])
print(expansion(universe, 1))
print(expansion(universe, 2))

['g a l a x y', 'c l u s t e r s']
['g  a  l  a  x  y', 'c  l  u  s  t  e  r  s']


__Second-Brightest Star__

In [27]:
def secondDimmest(stars):
    """Return an array of the second-brightest (second-largest) value from each row."""
    sorted_rows = np.sort(stars, axis=1) 
    return sorted_rows[:, -2]  # second largest per row

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print("Star clusters:\n", stars)
print("Second-brightest stars:", secondDimmest(stars))

Star clusters:
 [[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
Second-brightest stars: [1889 1647 1138 1863 1592]
